### ISSUE TITLE
refer to main site for non-platform-specific content in language READMEs

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#10]
(rather than let them all go stale)

**Comment by slimsag** [comment]
+1 highly agree

**Comment by bensigelman** [comment]
(with https://github.com/opentracing/opentracing.github.io/pull/19 done, I'm going to make appropriate changes to README's in `master` branches)

**Comment by yurishkuro** [comment]
@bensigelman is there any known outstanding tasks here? If so, let's enumerate as checkboxes and link to issues in respective repos.

**Comment by bensigelman** [comment]
@yurishkuro I think just https://github.com/opentracing/opentracing-python/pull/10 -- if you merge / LGTM that we are done.

**Comment by yurishkuro** [comment]
Merged, and closing this.
