### ISSUE TITLE
Can we introduce tags on the Tracer interface?

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.github.io#101]
Some of my users want to define tags that should apply to all spans coming from a service, like the git commit SHA. However, depending on the framework used to build the service, the tracer is sometimes initialized on their behalf elsewhere, so that they can only get a reference to `opentracing.Tracer`, not to a concrete implementation.

cc @bensigelman @dkuebric

**Comment by dkuebric** [comment]
Why would you want to redundantly tag spans?  I guess having it at the tracer level would allow the tracer to abstract it out and manage that themselves, but my first thought for something like git commit is have the instrumentation report it (and other service-level info) in top-level span for the service.

**Comment by yurishkuro** [comment]
@dkuebric it would be up to the tracer how to use tracer-level tags, it can attach them to all spans or to the first span in the process. It can also do various optimizations with those and send them out of process only once per whole batch of spans.  Basically I would expect the same level of support for tracer tags as for span tags, i.e. - no guarantees, but if the tracer does choose to persist those tags then the _traces_ can be found by the tag value.

**Comment by bensigelman** [comment]
@yurishkuro on the one hand I think this is a fine idea, but on the other I don't see why it needs to be a part of the OpenTracing spec yet... any Tracer implementation is welcome to take a set of tags to apply to all spans it creates, and that can be done cleanly at Tracer init time. If that pattern is particularly valuable, we can upgrade the concept to the OpenTracing layer and/or provide a `Tracer` adapter that defers all real work to some wrapped `Tracer` but interposes on `StartSpan` with the provided tags.

**Comment by dkuebric** [comment]
:+1:

**Comment by yurishkuro** [comment]
@bensigelman the problem is that the end user code has no way to give the Tracer a custom set of tags. If the code explicitly instantiates the Tracer implementation, then yes it can use a private API to pass any custom tags, but in many cases the tracer is instantiated by some common framework that the service is using, and the only way the service can get access to the tracer is via something like `opentracing.GlobalTracer()`.

**Comment by bensigelman** [comment]
@yurishkuro ah, I didn't read the issue carefully enough (you were clear about init time, I just didn't parse it correctly). Hm... It feels like an encapsulation failure to have some process subcomponent deciding which tags should apply to *all* spans in that process, esp if that subcomponent isn't important enough to have a say in process-level initialization. For spans originating in the subcomponent, something like the Tracer wrapper I proposed above would work well. If it's truly important for the tags to apply to *all* Spans started by the Tracer... then there's a problem. I'd be curious to talk through the specifics in more detail over VC if that works...

**Comment by yurishkuro** [comment]
We didn't find this to be a problem in real use cases, so closing.
