### ISSUE TITLE
Zipkin-style shared span vs two spans per RPC

### ISSUE THREAD

**Issue by dominikh** [opentracing/opentracing.github.io#102]
There are two popular ways of modelling RPC calls in tracing: Zipkin's
model, where both the client and the server share one span, and the
model in which a span is exclusive to a single tracer, causing client
and server to have two separate spans.

OpenTracing, as far as I can tell, has no opinion on which of the two
models should be used. However, OT's goal is to allow swapping out
OpenTracing implementations with a simple configuration change and to
have standardized instrumentation for popular libraries like gRPC. The
two models, however, require different use of the OT interfaces and
thus different instrumentation, which means that implementations
aren't truly interchangeable.

Has this topic come up before? Is this something that OT feels
responsible for and that should be addressed? This issue further
extends to things like logs, e.g. Zipkin's cs, cr, sr and sr, that
would need to be set for some tracers but not others.

**Comment by yurishkuro** [comment]
@dominikh 

> The two models, however, require different use of the OT interfaces

Actually, we've tried very hard to always accommodate Zipkin's "one span per RPC" model when designing OT API so that the instrumentation code is always the same. Our own (Uber's) implementations of OpenTracing are following Zipkin model, and we didn't have issues so far. Note that cs, cr, ss and sr are the internal details of the implementation, not something that the user of OT API need to care about.

**Comment by dominikh** [comment]
@yurishkuro Regarding the instrumentation: How do you deal with the fact that in the Zipkin model a span exists multiple times and will be Finished in multiple tracers, while in the other model that shouldn't happen? E.g. in a gRPC endpoint, in the non-Zipkin model, you wouldn't set data on or Finish the span that was extracted, while you would very much do that in the Zipkin model?

Regarding cs, cr etc: How do you deal with the fact that the tracer needs to know whether it's sending or receiving, in order to set the correct tags?

**Comment by yurishkuro** [comment]
@dominikh 

> How do you deal with the fact that in the Zipkin model a span exists multiple times and will be Finished in multiple tracers

That's no different from all other non-OT implementations of Zipkin tracers. We're not talking about the same span as in "the same object", there are two different spans, client and server, which just happen to share the same span ID. The Zipkin backend then merges them into one before showing to the UI.

> Regarding cs, cr etc: How do you deal with the fact that the tracer needs to know whether it's sending or receiving, in order to set the correct tags?

There is a standard tag `span.kind` that instrumentation is expected to set when creating client/server RPC spans, per http://opentracing.io/data-semantics/. It is true that if instrumentation code does not set this tag, then tracers doing two-spans-per-rpc would still work fine, where's Zipkin tracer will not be able to send cs/cr/ss/sr annotations correctly. But ¯\_(ツ)_/¯ - such instrumentation is not respecting the spec, nor is it providing sufficient data even to other tracers, as it is useful when a pair of spans were actually a single RPC call.

**Comment by dominikh** [comment]
> That's no different from all other non-OT implementations of Zipkin tracers. We're not talking about the same span as in "the same object", there are two different spans, client and server, which just happen to share the same span ID. The Zipkin backend then merges them into one before showing to the UI.

Right. But the difference here is that all OT implementations should share a similar feature set so that instrumentation needs to abide by the OT spec only and work across implementations. However, if your instrumentation uses the same span ID on two ends, but the specific OT implementation doesn't support that this won't be true anymore. And right now, as far as I can tell, the spec doesn't say whether implementations need to support it or not.

> There is a standard tag

I forgot about the standard tags, thanks. And to differentiate between sr and ss, you just set sr when creating the span, and ss when Finishing it?

**Comment by dkuebric** [comment]
@dominikh the instrumentation author shouldn't have to know about what the span ID is--that's handled completely by the tracer implementation.  The tracer implementation would also add sr/ss etc in this case.

The only thing the instrumentation author would do is generate a client-side span on the client side, propagate the tracer's context over RPC (which contains any IDs and other baggage the tracer needs, opaque to instrumenter), and generate a server-side span on the server side.  The tracer would be responsible for (and capable of) emitting the correct spans and tags in order to reconstruct a zipkin-style single-span RPC in the collection tier as zipkin does today.

**Comment by yurishkuro** [comment]
> instrumentation uses the same span ID on two ends

I'm not sure what you mean. The instrumentation (end user code or some RPC framework) does not even know what a "span ID" is, since that is an internal detail of the tracer implementation. If you're a client making outbound call, all you need to do is

```go
parent_span := opentracing.SpanFromContext(ctx)
span := tracer.StartSpan("downstream-call", ChildOf(parent_span))  // upcoming syntax
ext.SpanKind.Set(span, ext.SpanKindRPCClient)
tracer.Inject(span, opentracing.TextMap, HTTPHeaderCarrier(request.Header))
```

The server will do something similar except
```go
ext.SpanKind.Set(span, ext.SpanKindRPCServer)
```

**Comment by yurishkuro** [comment]
> And to differentiate between sr and ss, you just set sr when creating the span, and ss when Finishing it?

I suggest you take a look at [Uber's tracer implementation](https://github.com/uber/jaeger-client-go).

**Comment by dominikh** [comment]
> I'm not sure what you mean. The instrumentation (end user code or some RPC framework) does not even know what a "span ID" is

It doesn't know about span IDs, but it knows about spans, which have an identity. If the client injects a span, and the server joins/extracts that span, those two spans, per the OT spec, should represent the same span. Now the server can either set tags etc on that span and call Finish eventually, or it can just create a child span and work with that instead. These are two different ways of using OT, and not under the control of the OT implementation, but under the control of the instrumentation. Yet the OT implementation may only support or encourage one of the two ways.

**Comment by yurishkuro** [comment]
> and the server joins/extracts that span

Stop there, nothing more to be done. The server now has the span. Whether it's the same span ID as the client or not is not the server's concern, it's an implementation detail of the tracer.

> those two spans, per the OT spec, should represent the same span.

No, OT does not say anything about that. All it says is once you call `Join`, you get a span that server can work with. I see how that may be unclear, although [this PR](https://github.com/opentracing/opentracing.github.io/pull/100) makes is a bit more explicit:

```go
carrier = inbound_request.headers
span_context = tracer.extract(opentracing.Format.TEXT_MAP, carrier)
// Continue the trace given span_context. E.g.,
span = tracer.start_span("...", belongs_to=span_context)
```

**Comment by tinkerware** [comment]
In all fairness, how to propagate the tracing context back to a client is not explicitly spelled out in the spec as far as I can see. Here's the example from @yurishkuro, where the client propagates the context to the server:

```go
parent_span := opentracing.SpanFromContext(ctx)
span := tracer.StartSpan("downstream-call", ChildOf(parent_span))  // upcoming syntax
ext.SpanKind.Set(span, ext.SpanKindRPCClient)
tracer.Inject(span, opentracing.TextMap, HTTPHeaderCarrier(request.Header))
```

The server extracts the context (from https://github.com/opentracing/opentracing-go/pull/82) and starts its work:

```go
incoming_context = tracer.Extract(opentracing.TextMap, HTTPHeaderCarrier(request.Header))
server_span = tracer.StartSpan("server-work", RPCServerOption(incoming_context))
defer server_span.Finish()
```

Server injects the context from its span back into the response when it is done:

```go
tracer.Inject(server_span.Context(), opentracing.TextMap, HTTPHeaderCarrier(res_writer.Header))
```

If this is indeed how the API is intended to work, it _looks like_ OT requires the instrumenter to create a descendant span separate from "downstream-call" to represent the server-end of the RPC. In practice, if there were descendant spans on the server-side (e.g. "server-work") they can show up directly under "downstream-call" in a tracer dashboard, or if the server is not instrumented, it simply does not add a carrier to the response; the client can sulk away. There's simply no way for a server to propagate an _empty_ (that is distinct from _missing_) descendant context back to the client. Is my understanding correct?

Instead, if the server was supposed to inject the incoming wire context back into the response, then I don't see how the correct `span.kind` would be set in the carrier.

**Comment by yurishkuro** [comment]
> In all fairness, how to propagate the tracing context back to a client is not explicitly spelled out in the spec 

Tracing context is only propagated downstream, not upstream. Do you have a use case for upstream propagation?

**Comment by tinkerware** [comment]
My use case would be to allow an operator get an interactive trace for a request, similar to the trace request feature of the Cassandra command line tooling. If OT at least did not preclude upstream propagation, a tracer could allow a service to implement this sort of interactive tracing by propagating trace elements upstream and exposing an API to access it.

**Comment by yurishkuro** [comment]
On the wire propagation is only meant to carry "span context", which is a small set of ID fields and possible baggage. Returning the whole trace as part of the request is not a use case that was considered. It's especially suspicious as a use cases given that the serialized format of spans is a deeply internal aspect of the tracing implementation. 

The trace collection is meant to be asynchronous and out of process. I don't think your use case specifically requires upstream propagation, all you want is to (a) trigger trace collection (i.e. override any sampling decision), and (b) have a way to access the trace from the tracing system, possibly via UI. You can still do these things, with a bit of help of the edge application that starts the trace:
 # you add a parameter to the application request (e.g. in the headers) stating that you want this request traced regardless of the sampling decisions made by the tracer.
 # ideally this parameter will carry a unique ID that you can use to locate the trace afterwards
 # the edge application can do the following

```
if debug_request := request.Header["debug_request"]; debug_request != nil {
    span := opentracing.SpanFromContext(ctx)
    ext.SamplingPriority.Set(span, 1)
    span.SetTag("debug_request", debug_request)
}
```

Most tracing implementation will guarantee that this trace will be captured, and you'll be able to find it in the UI by searching for a tag `debug_request` with the unique ID provided in the original request.

**Comment by bensigelman** [comment]
@tinkerware there are substantial observer effects involved with sending complete trace data in-bound with the request/response pair (which is why the distributed tracing systems I'm aware of send the data out-of-band). But it is an interesting feature request, esp where baggage is concerned... worth thinking through and prototyping if you have the cycles.

**Comment by tinkerware** [comment]
@yurishkuro The same thing occurred to me too; thanks for thinking it through. Depending on the async trace collection would mean you have to wait to make sure the particular trace you are interested is collected, and there's no simple way to figure out that a trace you get this way is incomplete (missing spans). On the other hand, it would be fairly easy to compose from existing pieces; can be handy in a pinch.

@bensigelman I agree that sending trace data in-band perturbs the system too much to be of regular use in normal operation. I really thought of this as an interactive debugging tool for an operator, where they can craft a request and immediately get a trace with the response, allowing them to iterate faster during development or production; consider it as an "explain" command for services.

**Comment by bensigelman** [comment]
@dominikh what criteria are we using for keeping this issue open vs closing it? Do we want to add some documentation somewhere on opentracing.io?

**Comment by dominikh** [comment]
@bensigelman I think this issue can be closed without further action. The new API with SpanContexts alleviates the confusion.

**Comment by bensigelman** [comment]
@dominikh SGTM.
