### ISSUE TITLE
pathetic logo

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#11]

**Comment by bensigelman** [comment]
![image](https://cloud.githubusercontent.com/assets/2251553/12213355/894e6608-b62b-11e5-80c3-b00c06fb1938.png)

?

**Comment by slimsag** [comment]
I made this one for fun (don't feel obliged to use it.. I'm no artist by far, hah) -- I kindof like yours better, actually, but am cool with whatever everyone else likes and we can always change it.

![opentracing](https://cloud.githubusercontent.com/assets/3173176/12214706/a50037d8-b65c-11e5-8157-b744b4d7b72a.png)

**Comment by bensigelman** [comment]
We will *definitely* change it if we use mine! :)

On Friday, January 8, 2016, Stephen Gutekanst <notifications@github.com>
wrote:

> I made this one for fun (don't feel obliged to use it.. I'm no artist by
> far, hah) -- I kindof like yours better, actually, but am cool with
> whatever everyone else likes and we can always change it.
>
> [image: opentracing]
> <https://cloud.githubusercontent.com/assets/3173176/12214706/a50037d8-b65c-11e5-8157-b744b4d7b72a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentracing/opentracing.github.io/issues/11#issuecomment-170200865>
> .
>


-- 
Sent via mobile

**Comment by slimsag** [comment]
I'm in favor of yours. I don't like mine at smaller resolutions as it looks too much like a pixelated box :)

**Comment by bensigelman** [comment]
Mine looks too much like a gender symbol right now... it's really not the right thing for me to spend time on this second, but I (or perhaps my wife, who does design on the side) will figure something out before it's too late :)

**Comment by adriancole** [comment]
of the two proposals so far, I like @slimsag better

**Comment by bensigelman** [comment]
I don't like either :)

I think mine sucks and looks like a ♀ or ♂. I think @slimsag's is too busy and won't scale down well as a logo. I made a rule for myself not to spend another minute working on a logo until the docs were all in place, though :)

**Comment by bensigelman** [comment]
I decided to bring in some professional help (for an amazingly low $ cost... 99designs is an amazing deal IMO!).

http://99designs.com/logo-design/vote-8yhryi

More context here:

https://gitter.im/opentracing/public?at=56b23f8634ca6b3f59445af1

**Comment by slimsag** [comment]
Nice! Love it :)

**Comment by bensigelman** [comment]
The final poll after a final set of revisions from the various designers:

https://99designs.com/logo-design/vote-kgg8o8

**Comment by bensigelman** [comment]
done, per #50.
