### ISSUE TITLE
Add CNCF text / logo to website

### ISSUE THREAD

**Issue by caniszczyk** [opentracing/opentracing.github.io#126]
Now that OpenTracing is a CNCF project, usually a blurb on the website or main project README is a nice thing for us. See the Prometheus site for an example: https://prometheus.io/

**Comment by caniszczyk** [comment]
![screen shot 2016-10-11 at 2 46 36 pm](https://cloud.githubusercontent.com/assets/63777/19285917/8c8702f6-8fc1-11e6-8bd4-eae9c120e4f9.png)

**Comment by bensigelman** [comment]
@caniszczyk will do!

**Comment by bensigelman** [comment]
cc @pritianka @reimertz

**Comment by reimertz** [comment]
any idea how this should look like @fractaly?

**Comment by bensigelman** [comment]
![image](https://cloud.githubusercontent.com/assets/2251553/19587536/f23656de-9713-11e6-8808-36a75efb0511.png)


Thanks @reimertz!
