### ISSUE TITLE
The build doesn't work for me

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.github.io#127]
First, `npm run dev` fails when the default Node installation is 0.10, we should specify in the readme which minimal version is required, or better yet add `.nvmrc` file so that people can just  run `nvm use`.

Once I got it to compile, the server at http://127.0.0.1:4000/ just shows the directory.  I had to rename the file `$ mv _site/index _site/index.html` to show the home page.

cc @reimertz

**Comment by reimertz** [comment]
@yurishkuro PR above should solve your issues. Please pull it and confirm, if see, let's push it to master.

also, thanks for helping me sorting out all these small things. 👍

**Comment by reimertz** [comment]
@yurishkuro can we close this issue now?

**Comment by yurishkuro** [comment]
ok, thanks
