### ISSUE TITLE
Provide more details comparison to related systems

### ISSUE THREAD

**Issue by remmeier** [opentracing/opentracing.github.io#135]
Could you elaborate in "why OpenTracing"? => http://opentracing.io/documentation/

e.g. zipkin is already quite popular and has support for different programming languages. Where are the benefits and differences of OpenTracing?

**Comment by bensigelman** [comment]
@remmeier the page in question already addresses your question:

> Contemporary distributed tracing systems (e.g., Zipkin, Dapper, HTrace, X-Trace, among others) aim to address these issues, but they do so via application-level instrumentation using incompatible APIs. Developers are uneasy about tightly coupling their polyglot systems to any particular distributed tracing implementation, yet the application-level instrumentation APIs for these many distinct tracing systems have remarkably similar semantics.

This is particularly important for common OSS software components (RPC systems, etc) which need to support tracing but wish to avoid tight coupling to any particular tracing framework.

**Comment by remmeier** [comment]
I guess what for java logging is slf4 will be opentracing.io at some point for tracing libraries, but no protocol specification, etc.
