### ISSUE TITLE
first public rev of javascript API

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#17]
@adriancole @yurishkuro @slimsag 

My cofounder and overall great-guy @bcronin has been getting going on OTAPIs for javascript, with an eye both towards Node.js and, of course, the browser. I'll assign this to him, but wanted to let you all know about it.

**Comment by yurishkuro** [comment]
@oibe who did an internal Node.js version at Uber, with slightly different naming since it was before we standardized.

**Comment by bensigelman** [comment]
https://github.com/opentracing/opentracing-javascript/pull/2
