### ISSUE TITLE
Use site generator

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.github.io#2]
- [ ] need a theme that supports multi-page navigation
- [ ] basic setup of the generator project
- [ ] agree on markup language
- [ ] migrate home page

**Comment by bensigelman** [comment]
I am fine writing as much copy for this as people want. I don't have strong opinions about particular site-generation options just so long as they are not complex :)

**Comment by adriancole** [comment]
@abesto @rtyler any opinions on simple site generation state of the art?

**Comment by slimsag** [comment]
I've had good experiences with https://gohugo.io/

**Comment by yurishkuro** [comment]
I've got the basic layout going with Jekyll using Hyde theme. PR #3

![screen shot 2015-12-31 at 2 30 35 am](https://cloud.githubusercontent.com/assets/3523016/12062249/a1c342d8-af66-11e5-872d-5a8e967e9ea2.png)

**Comment by abesto** [comment]
My current favorite is Jekyll, #3 makes me happy :)
