### ISSUE TITLE
need some way (pan-platform) to record a Span that happened in the past

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#20]
I was talking with a user yesterday that has a log file of what's essentially span data coming from what we can think of as a black-box process, and they want to get it into an OTAPI-compatible system. This would be easy if there were a way to construct Spans after the fact (but there's no such API). It's similar to the `RawSpan` concept from `api-go`, but that's not part of `Tracer` per se.

**Comment by adriancole** [comment]
This is also a use-case in Brave. For example, it has a LocalTracer, which
I've used to record historical events of interest. For example, bootstrap
events.

Minimally, this required the ability to supply a timestamp on start and a
duration on finish.

**Comment by slimsag** [comment]
I don't have a particular use case in mind at the moment, but I completely agree this is a good idea.

If I understand correctly, the only requirement would be to explicitly set the start time and duration of a given span? What if we added those as simple methods to the `Span` interface ala `SetPastTime(start time.Time, duration time.Duration)` or something of the sort? This way you'd be able to use the same API for emitting data as you would normally, instead of going through RawSpan etc.

**Comment by yurishkuro** [comment]
@bensigelman Exactly the use case I had when I wrote my original opentracing-go module, we have mobile apps collecting tracing data and submitting them through a completely different channel, and on the server side those tracers are getting converted to "real" traces with externally provided timestamps. In that implementation I dealt with this via optional `Options` argument to start/finish methods

https://github.com/uber-common/opentracing-go/blob/master/options.go#L32

**Comment by yurishkuro** [comment]
Another similar use case we're working on right now is we want haproxy to add Logs to the current trace that's passing through it. We already have something in place that can sniff headers from passing requests and write the out to kafka along with some timers. The plan is to have a custom reader of that kafka topic that will extract the timestamps and trace IDs of when the request was passing through haproxy and create additional span Logs that will be saved to Cassandra via somewhat of a back door.  It would be nice to have a clean OpenTracing way of doing that, which requires not only the ability to inject the timestamps into Logs externally, but in our case do that without starting/finishing the span.  I know Ben you will be against that last part :-), and say we could just create a new span instead, but doing so would require modifying in-flight request inside haproxy to replace the client trace/span ID with haproxy span ID, and that is much more intrusive way of doing it vs. just adding logs.

**Comment by bensigelman** [comment]
There are also the various logging methods (that also have implicit timestamps)... Kind of a shame to go and build up the spans (and their constituent logs) incrementally when for the after-the-fact case all of the data is already available (i.e., it would be possible to save some churn and allocation). Though I hate to preoptimize, etc, etc.

And yes, @yurishkuro, I remember the `XYZOptions` from the original uber-common go lib. I am torn between something like that and something that looks a lot like `RawSpan`. This is an important case to support, but also an uncommon case, and I would be happy if this after-the-fact use case didn't leak into the more-commonly-accessed parts of the API.

Oh, just saw your second message: so you basically want to be able to record logs independent of spans?

**Comment by yurishkuro** [comment]
I agree that it's cleaner not to pollute the core API with "historic" options. But I feel that exposing people to yet another dimension of the data model like RawSpan is not the way to go. Instead we can have the tracer expose a different HistoricTracer API (via composition), which will look exactly like the main Tracer API, but all methods would accept the additional timestamp and whatever else may be needed. Supporting this is slightly more work for the implementors, but leaves the users to deal with essentially the same data model as the core api (I admit it does sound clunky).

**Comment by bensigelman** [comment]
Yeah, not a lot of great options, esp for Go given the non-option of overloading(*).

I put this issue on the v1.1 milestone since I don't want it to distract from getting parity across the existing platforms – make sense?

(*): Go does kinda/sorta support sketchy overloading for a single final param via varargs... something like

```
    // Caller should provide exactly zero or one `StartOptions` params; Other behaviors are undefined.
    StartSpan(opName string, opts ...StartOptions)
```

... as opposed to passing `nil` like in the original `uber-common` lib. Of course there's a defensible argument that the above is an anti-pattern!

Anyway, just an aside.

**Comment by yurishkuro** [comment]
ok with 1.1

I think the problem is not only in Go, especially for methods that already take varargs like info(). Even in Java, the signatures may clash

```java
Span info(String message, Object... args);
Span info(String message, Options options, Object... args);
```

**Comment by bensigelman** [comment]
yes, that's true...

**Comment by adriancole** [comment]
what if we put the timestamp as arg0?

**Comment by bensigelman** [comment]
I would be excited to keep the interfaces for real-time instrumentation of application code as clean and intuitive as possible (which implies that the timestamp would be recorded implicitly, not as a 0'th param).

I don't have a concrete proposal for this until I think about it more... I'm going to return to getting the "semantic spec" nailed down – need to finish the next rev tonighT!

**Comment by bensigelman** [comment]
I'm marking this as a dup with #22 (and will close this Issue as such).
