### ISSUE TITLE
Should we declare encoder and decoder separately?

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing.github.io#21]
If the encoder and decoder are incompatible, they will cause errors for sure. Having to declare two types with similar documentation, seems a recipe for typos, plus clutters the namespace.

Do we feel TraceContextEncoder and TraceContextDecoder really need to be separate types? How about just TraceContextCodec?

**Comment by bcronin** [comment]
For the reasons Adrian gave, I'd also support the notion of a single TraceContextCodec type.

Unless of course there's a good reason to keep them separate that I'm not considering :)

**Comment by yurishkuro** [comment]
In the original https://github.com/uber-common/opentracing-go I had the interfaces split but along a different dimension, binary vs. string, and client would ask the tracer "give me string codec". But since we're not considering other types of serialization besides text and binary, I'd be in favor of merging these two as well.

**Comment by bensigelman** [comment]
Me four. So we'll do this? v1.0 or v1.1? (I'd vote for the former, esp if we're trying to be honest about semver)

@bcronin and I were chatting this AM (we sit next to each other :), and there's a case for collapsing more of these interfaces into `Tracer` and just using loud comments/etc to delineate the boundaries between the pieces that have to do with span-starting vs the pieces that create TraceContexts vs the pieces that do codec of same. Inheritance in interfaces – especially when the bottom line is that `Tracer` implements essentially everything – can make things harder to grok, even if our intention is to honor a separation of concerns.

If there's an appetite for the above I'll open a separate issue.

**Comment by yurishkuro** [comment]
+1 for merging codecs in v1.0

There are definitely benefits in keeping everything that Tracer can do in one place. Especially for dynamic languages - I was able to kludge Python version with multiple inheritance, but it was weird, and in Javascript - phhhhh...  So +1 to that too.

**Comment by bensigelman** [comment]
Okay, I'll create a separate issue to track The Great Interface Consolidation.

**Comment by slimsag** [comment]
+1

**Comment by adriancole** [comment]
Made this comment in api-java, but languages should be able to choose
composition or inheritance. The big hierarchy is actually an antipattern in
java. Composition is well documented as being favorable to inheritance, and
systems are designed to encourage it. For example, Dagger (a wiring system
by Google and Square) explicitly makes components (vs big inheritance)
preferred.

I don't want to make python worse, and I think we do have an opportunity to
allow languages to be idiomatic with more modern style. If there's a
language that requires hierarchies to do things like add codec, well allow
them, but don't require folks to conflate concerns elsewhere.

Last thing we want is for api-java to be a showcase of what *not to do*.
And of course similarly in other languages.

**Comment by yurishkuro** [comment]
@adriancole I think this can be closed, as the codecs were merged into a single Popagator API

**Comment by yurishkuro** [comment]
the interfaces are consolidated in the current API, and are getting split again per https://github.com/opentracing/opentracing-go/pull/48#.

I suggest we close this.

**Comment by bensigelman** [comment]
Let's give it 24h for objections, but, if there aren't any, I agree.
