### ISSUE TITLE
change the per-platform repo naming convention?

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#23]
(@breerly)

Per https://github.com/opentracing/api-go/issues/34, should we name the PlatformX repo `opentracing-platformx` rather than `api-platformx`?

This makes forks friendlier from a naming standpoint and is a convention adopted by other polyglot github orgs. On the other hand, it adds some stuttering... e.g., in Go,

```
import "github.com/opentracing/opentracing-go/opentracing"
```

:)

**Comment by yurishkuro** [comment]
I'm ok with renaming.  I wonder if we need to keep the last `opentracing` part in Go. Many Go projects put the core files in the root directory, so the path in the import would be `opentracing-go`, but the package name will be `opentracing`. Not sure if it'd work...

**Comment by slimsag** [comment]
- +1 for `opentracing-platformx` and keeping it consistent across all languages.

I agree with @yurishkuro -- lets change the Go import path to:

```
import "github.com/opentracing/opentracing-go"
```

Package name does not need to match final path element, and in my (very large) experience often does not.

**Comment by adriancole** [comment]
in favor of "opentracing-java" as api is an implied minimum publication of
that repo.

**Comment by adriancole** [comment]
done.. https://github.com/opentracing/opentracing-java/issues/3

**Comment by bensigelman** [comment]
Great, thank you! I will handle `s/api-go/opentracing-go/g`

**Comment by bensigelman** [comment]
Done -- thanks, all.

https://github.com/opentracing/opentracing-python/commit/786f4485c820a230512332ea00007a2ebdd9dc1c

https://github.com/opentracing/opentracing-java/commit/9765e07aced2ba7769de9b0e3866e6afc5cf7824
