### ISSUE TITLE
consolidate the myriad interfaces into Tracer

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#24]
@bcronin and I were chatting this AM (we sit next to each other :), and there's a case for collapsing more of these interfaces into Tracer and just using loud comments/etc to delineate the boundaries between the pieces that have to do with span-starting vs the pieces that create TraceContexts vs the pieces that do codec of same. Inheritance in interfaces – especially when the bottom line is that Tracer implements essentially everything – can make things harder to grok, even if our intention is to honor a separation of concerns.

On #21, @yurishkuro added:

> There are definitely benefits in keeping everything that Tracer can do in one place. Especially for dynamic languages - I was able to kludge Python version with multiple inheritance, but it was weird, and in Javascript - phhhhh... So +1 to that too.

**Comment by slimsag** [comment]
FWIW I agree with this, but I'm not sure of the details exactly. I'd like to see it in code before giving my final opinion.

**Comment by adriancole** [comment]
Heh looks like this topic came up in 3 places! Short of it is that we want
things to be easy to grok, and clean in the target language. In some cases,
like java, composition will be far more preferred over inheritance.

Each part is simpler to understand and multiple inheritance for orthogonal
concerns is a deprecated practice (composition is the current way)

Iotw something doesnt have to be a codec to start traces! The actual call
sites are orthogonal, and mixing all concerns in an uber interface can
cause some languages (like java) to be nastier to use and implement.

**Comment by slimsag** [comment]
I think @adriancole raises an interesting point, maybe we shouldn't strive for a 1:1 API across all languages but instead for 1:1 _features_ and write it in the language however you normally would, e.g. in Go using composition instead of a monolithic interface, and in Python and Javascript using a single Tracer object / in one place if that's most idiomatic to that language.

Thoughts @yurishkuro @bcronin ?

**Comment by bensigelman** [comment]
@slimsag I'm 100% (110%? What's my allowance?) in favor of semantic parity rather than API parity... that's the whole point of the intentionally-prose-rather-than-pseudocode "semantic spec" page we've been working through.

**Comment by bcronin** [comment]
For what it's worth, my metric is simply if a user of OpenTracing is familiar with it in language A, it should be intuitive for her to use OpenTracing language B. That's pretty flexible constraint, so I think there are a lot of different approaches that could work.

(This is getting ahead of where we are, but if there are features that'd be really nice to have that are *not* 1:1 with the other platforms, I think having `opentracing-<platform>-util` repos could be a workable solution. As long as they're clearly called out as separate from the core namespace / package, users understand those things will not necessarily translate across platforms. For example, the util package in JS might have convenience functions for automatically wrapping functions in spans - something general nice to have, but does not belong in the core library and *shouldn't* require standardization across languages. That said, I'd push to not worry about `util` packages until we need to!)

**Comment by dankosaur** [comment]
@bcronin agreed, there's a lot of syntactic sugar that will be language-dependent.  What we ended up doing for this @ AppNeta was providing 2 APIs in each language.  The "low-level" API is pretty much exactly the same in every language (most implementations use bindings to a c library that powers this API).  The "high-level" API provides convenience methods built on top of the low-level API.  These latter are usually dependent on some language-specific paradigms.  So +1 for `util` or similar packages down the road.

**Comment by bensigelman** [comment]
This is the closest thing I have to a concrete proposal to address this issue: https://github.com/opentracing/opentracing-go/pull/40

Here's what I'm planning to do:
- clean up that PR (there's some horrendous stuff in the "standard" impl which can't in good conscience make it into `master`)
- intentionally not-resolve some of the ancillary issues that have come up during the review (namely the fate of `SetTraceAttribute`): that's an important topic but is blocking progress on this unrelated and important cleanup
- try to merge the result into `opentracing-go`
- make the `.md` spec match up with the above
- make the other languages consistent

**Comment by bensigelman** [comment]
@yurishkuro the remaining thing here is getting .py to line up... do you want me to take a crack at that?

**Comment by bensigelman** [comment]
the python version of this is merged... closing.
