### ISSUE TITLE
opentracing.com

### ISSUE THREAD

**Issue by breerly** [opentracing/opentracing.github.io#40]
![screen shot 2016-01-25 at 11 25 02 am](https://cloud.githubusercontent.com/assets/263587/12561699/561dd70e-c356-11e5-8931-1e5d80154e35.png)

Ideally this is purchased and redirects to `opentracing.io` - exact-match .com's tend to win in the SEO world, I would hate for this project's findability to be negatively affected by whoever buys this domain.

**Comment by slimsag** [comment]
Closed for less visibility, but I completely agree. @bensigelman who got the opentracing.io domain ? do they want to grab this one too? If not I can pick it up.

**Comment by bcronin** [comment]
Done. I added the .com to the same account as the .io and the redirect should happen once the DNS has propagated.

**Comment by bensigelman** [comment]
thanks for checking, folks :)
