### ISSUE TITLE
clearly explain why JoinTrace requires an operation name

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#58]
Per https://gitter.im/opentracing/public?at=56c3ebf3c26982646215b5c7

@adriancole

**Comment by bensigelman** [comment]
From http://opentracing.io/spec/#inject-and-join

> Join examines the carrier and tries to extract identifying information needed by the new Span instance it’s trying to create. **Join also accepts an operation name for that Span (since it’s typically not included within the carrier).**

**Comment by adriancole** [comment]
SGTM
