### ISSUE TITLE
RFC: s/Trace Attributes/Baggage/g

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#67]
Per https://github.com/opentracing/opentracing.github.io/pull/47#issuecomment-186927212:

> I had a nice VC with Rodrigo Fonseca and Jonathan Mace (author of the excellent PivotTracing paper among other things) and I started to like the term "baggage" since real-life baggage is something you "carry with you", much as these key:value pairs are carried with the trace. So I am open to something like SetBaggage/GetBaggage; it's a non-standard name, but it's also a non-standard idea and would maybe help to get users to actual RTFComments (a particularly good thing in this case).

This would just be a rename (i.e., semantics are exactly like Trace Attributes).

**Comment by yurishkuro** [comment]
are we going to do it as rc2?

**Comment by bensigelman** [comment]
I was going to leave this here to see if people complained or not... but if we have rough consensus then RC2 seems like a good plan!

**Comment by dkuebric** [comment]
:+1:

**Comment by yurishkuro** [comment]
+1 to rename. It's a funny term, first time people hear it it sounds odd, but then it grows on you. I think everyone who was at that presentation immediately recognizes what "baggage" means, as opposed to trace attributes.

**Comment by bg451** [comment]
+1

**Comment by bensigelman** [comment]
The above seems like critical mass to me... Let's do it.

- [ ] Docs site @bensigelman
- [ ] Go @bensigelman
- [ ] Go `basictracer` @bensigelman
- [ ] Python @bensigelman
- [ ] Java @michaelsembwever
- [ ] PHP @wladekb

If anyone wants to take one of the above from @bensigelman, just ping me on gitter or something. I don't want to meddle with Java or PHP since they are in-progress.

**Comment by wladekb** [comment]
PHP done in:
https://github.com/Wikia/opentracing-php/commit/4e14889b13c632e882201b5a927f2f8d121b3761
https://github.com/Wikia/opentracing-basictracer-php/commit/fe23e8ce2f1e49668be777f36b096f6bf016bb49

**Comment by bensigelman** [comment]
@wladekb thanks!

**Comment by bensigelman** [comment]
@bg451 and I communicated off-list about taking this opportunity to break the `opentracing-go` :arrow_right: `basictracer-go` dependency... otherwise this change cannot be made without breaking one or the other temporarily.

**Comment by bensigelman** [comment]
Ok... all done except for the pending Java work. Thanks, everyone.

**Comment by bensigelman** [comment]
I'm going to close this since the Java code is still sitting in various PRs...

**Comment by michaelsembwever** [comment]
Tackled as part of https://github.com/opentracing/opentracing-java/pull/10
