### ISSUE TITLE
Restrict character set in tag names to allow easy encoding as HTTP headers

### ISSUE THREAD

**Issue by wladekb** [opentracing/opentracing.github.io#68]
As it occurred in https://github.com/Wikia/opentracing-php/issues/3

The basictracer implementation in Go defines tags here:
https://github.com/opentracing/opentracing-go/blob/master/ext/tags.go

```go

var (
	// PeerXXX tags can be emitted by either client-side of server-side to describe
	// the other side/service in a peer-to-peer communications, like an RPC call.

	// PeerService records the service name of the peer
	PeerService = stringTag("peer.service")

	// PeerHostname records the host name of the peer
	PeerHostname = stringTag("peer.hostname")

...
```

If one would like to put the tag names directly as HTTP headers he would need to take an extra effort to encode the dots.

It would be great if that could be avoided.

**Comment by dkuebric** [comment]
@wladekb a wider range of chars is currently allowed in tags, which are intended to be reported with the span and not intended to be serialized across the wire, as opposed to trace attributes (to be renamed to "baggage"), which are intended to be serialized across the wire and propagated in band with the trace.

Can you share a use-case for sending tag names as HTTP headers?

**Comment by bensigelman** [comment]
@wladekb any thoughts about @dkuebric's question above (which I share)?

**Comment by wladekb** [comment]
I would consider the suggestion invalid after I got better understanding of what is the primary purpose for tags and baggage (trace attributes) and what goes where. Feel free to close it.

**Comment by bensigelman** [comment]
Sold :) Thanks.
