### ISSUE TITLE
Make the Tracer inject/join (i.e., propagate) directly rather than through an additional delegation layer

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#70]
At present, the [OT semantic spec](http://opentracing.io/spec/) has both a `Tracer.injector(format)` method/concept and an `Injector.inject()` method/concept. Strictly speaking this is not necessary, though OT implementations could (or could not, whatever) choose to create helper libraries that would have similar abstractions. To review, at present the injection code path looks (in pseudo-python) like:

```
some_carrier = SomeCarrier()
my_tracer.injector(Format.SOME_FORMAT).inject(span, some_carrier)
```

It could alternatively look like...

```
some_carrier = SomeCarrier()
my_tracer.inject(span, Format.SOME_FORMAT, some_carrier)
```

... or, in languages with stronger types, even just ...

```
someCarrier := NewSomeCarrier()  // each carrier gets its own type
myTracer.Inject(span, someCarrier)
```

(i.e., no `format` argument as a type specifier)

----------------

The above also came up here: https://github.com/opentracing/opentracing-java/pull/10/files#r53574474 and here: https://github.com/opentracing/opentracing-go/pull/48#issuecomment-181047181; @tschottdorf said:

> Maybe I'm not reading this right, but are you basically suggesting going towards opentracing/opentracing-go#48 (comment)? I.e. (this is copy-pasta from there):
> 
> ```
> type Tracer interface {
>   // Join attempts to obtain a Span from the given interface.
>   Join (interface{}) (Span, error)
> }
> 
> type Span interface {
>   // Inject attempts to store the Span's information in the given interface.
>   Propagate(interface{}) error
> }
> 
> t := something.NewTracer()
> sp := t.StartTrace("foo")
> var req http.Request
> // This will add the trace information to the request's headers.
> if err := t.Propagate(&req); err != nil {
>   return err
> }
> 
> // Receiving end uses the Tracer to join a new Span onto the one
> // encoded in the Request.
> if sp, err := t.Join(&req); err != nil {
>   // ...
> }
> ```

---------------------

I'm not sure if I'm to the point of advocating for the current approach or the simplified version that has fewer types/concepts (as there are some advantages to each), but I wanted to make sure that we were intentional as a group about which path we take.

Curious to hear thoughts from those who've had opinions along these lines thus far: @yurishkuro @michaelsembwever

**Comment by yurishkuro** [comment]
I am in favor of the syntax that accepts the format:
```
some_carrier = SomeCarrier()
my_tracer.inject(span, Format.SOME_FORMAT, some_carrier)
```
even for languages that could derive the type from the carrier directly, because:
 * some languages cannot do it and I prefer to keep the API similar across all languages
 * it permits the same carrier (e.g. a byte array) to be used with different formats

**Comment by bensigelman** [comment]
@yurishkuro definitely agree in Python, so your first bullet makes sense to me... the second is less clear, per

```
package main

import (
	"fmt"
	"reflect"
)

type B1 []byte
type B2 []byte

func printType(i interface{}) {
	fmt.Println("Type: ", reflect.TypeOf(i))
}

func main() {
	printType(B1{})
	printType(B2{})
}
```
which yields
```

**Comment by yurishkuro** [comment]
@bensigelman yes, in Go, but not in Java, e.g. `ByteBuffer` (unless you extend it). There's also another difficulty with reflection based approach. If you recall, I had a proposal for a split Carrier that was an interface, not a struct. So a tracer needs to have two features, 

(a) registering a custom injector based on type, probably:

```java
public void registerFormat(Class<CarrierInterface>, Injector, Extractor)
```

(b) locating that injector by a concrete implementation of `CarrierInterface` - cannot do map lookup for that, need to iterate through all registered injectors and see if passed carrier is an instance of the registered interface. One could cache that lookup, but would need a mutex.

Meh. Not saying it's not doable, just a lot of noise. 

But if people feel strongly about not providing the format in strongly typed langs, I can live with that.

**Comment by bensigelman** [comment]
No strong feelings, just wanted to get the arguments out there.

I also meant to say that (obviously) the same arguments apply to the Extractor.

**Comment by bensigelman** [comment]
Per something embedded within https://gitter.im/opentracing/public?at=56ce56bfbfb1cf9a7ff2deed, I propose that we move forward with the middleground simplification... As @yurishkuro put it:

```
some_carrier = SomeCarrier()
my_tracer.inject(span, Format.SOME_FORMAT, some_carrier)
```

If there are objections, please raise them soon... if nobody complains within 48h we will move forward with this simplification. (Some people who have been active lately and might care (in alphabetical order): @adriancole @bcronin @bg451 @dkuebric @michaelsembwever @tschottdorf @wladekb @yurishkuro)

Thanks!

**Comment by michaelsembwever** [comment]
I will add this to https://github.com/opentracing/opentracing-java/pull/10

It would be nice if the Specification can state that format is an optional parameter, depending on the language.

**Comment by michaelsembwever** [comment]
Furthermore, I'd like an API that allows in the future true IoC, for example

    Tracer {
        ...
        public void register(Injector injector);
        public void register(Extractor extractor);
    }

    public interface Extractor<T> {
        boolean canHandle(Object carrier);
        Span joinTrace(String operationName, T carrier);
    }
    public interface Injector<T> {
        boolean canHandle(Object carrier);
        void injectSpan(Span span, T carrier);
    }

The injector/extractor and registration process now resides outside of the public api, so I believe this is a possible step forward to take.

**Comment by bensigelman** [comment]
@michaelsembwever 

> It would be nice if the Specification can state that format is an optional parameter, depending on the language.

So far the only type system that really makes the above feasible is Go (per @yurishkuro's comment on the pending Java code: https://github.com/opentracing/opentracing-java/pull/10#discussion_r54183176), and even there we have been using the `format` arg for clarity.

I do like the "true IoC" vision that you outlined above.

**Comment by bensigelman** [comment]
> if nobody complains within 48h we will move forward with this simplification.

Well, it's been about 48h... I will move forward with this change in Go and Python soon (maybe this weekend?). Speak now or forever hold your peace, etc :)

**Comment by bensigelman** [comment]
Go and Python have the revised semantics, Java is en route, and I will update the main docs site later today...

**Comment by bensigelman** [comment]
(I'll wait to close this until the pending JS and PHP APIs incorporate these simplifications... @bcronin @wladekb)

**Comment by bensigelman** [comment]
Not sure of current status of (unmerged) PHP lib, but the latest JS code has inject/join... I'll close this.
