### ISSUE TITLE
Add Tracer.Flush() on all platforms?

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#74]
There are two important use-cases for Tracer.Flush():
- process shutdown (graceful or ungraceful)
- tests

That said, a Tracer that does no buffering has no need for a Flush() method, so in that sense we would be making (potentially inaccurate) assumptions about Tracer implementations.

OT users could alternatively manually maintain a reference to the actual Tracer impl type and call Flush() on it directly (in signal handlers, in unit tests, at the end of main(), etc)... In my mind, though, buffering will be so widespread that Tracer.Flush() is worth factoring into the main API, even if it's a noop for some impls.

See also: https://github.com/opentracing/opentracing-go/issues/66

**Comment by yurishkuro** [comment]
I like having Flush, but could be persuaded otherwise. I don't know of a use case that cannot be solved without public Flush() method.

**Comment by bensigelman** [comment]
If there are no objections, I propose that we add Tracer.Flush() to the spec (and the various platforms)... Let's wait >= 48 hours to see if there are concerns.

I'll cc some folks who might care: @yurishkuro @tschottdorf @dkuebric @michaelsembwever @adriancole @wladekb @bcronin

**Comment by michaelsembwever** [comment]
any asynchronous implementation in Tracer should be providing and connecting its own shutdown hooks. and client code needs to be able to configure the asynchronicity, ie when writing crash-only software.

i can only see a need for this at the test level, and then this becomes test-pollution.
in most languages i'm pretty sure that tests can access non-api methods (via package-protected scope or via subclassing).

but i have no strong objections.

**Comment by bg451** [comment]
I'm fairly neutral on this, but overall it seems like a net gain.

**Comment by yurishkuro** [comment]
As I've been implementing tracers in several languages now, I am now inclined to say that we shouldn't require Flush() and leave this function to the implementation. Main reasons:
 1. as was already stated, there doesn't seem to be a strong production use case for this, at least not one that cannot be solved without such official method
 1. if we did require it, we would need to debate which exact async API such method would implement (blocking, future, callback, etc.)
 1. the overall semantic meaning of flush() is not clear, at least vs. Close(). With Close() the tracer can stop accepting/reporting new spans, and therefore the "flush" step is well-defined. But with plain flush(), especially called in the middle of the run, tracer may still continue receiving spans, so when is flush() supposed to return?

**Comment by bensigelman** [comment]
I'm swayed by @michaelsembwever and @yurishkuro's arguments and – after doing some more digging into our own (non-public) code – I'm realizing that the sort of "process exit and signal handler" code can be designed to have access to the OT *impl*, thus allowing it to provide a "flush" method as needed.

I can still see us adding something like this in a while (given enough evidence of its ubiquity in implementations), but there's no urgency.

So: I will *close* this issue in 48h unless there are objections :)

**Comment by bensigelman** [comment]
Resolved unless new information arises: `Tracer.Flush()` (or `Close()` or similar) are the responsibility of implementations and not part of the OT API proper.
