### ISSUE TITLE
finish main opentracing.io static site

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.github.io#9]
- [x] briefly explain the raison d'etre for tracing systems (visibility, etc)
- [x] briefly explain the raison d'etre for opentracing (flexibility, decoupling, etc)
- [x] point to language-independent "semantic spec" (#8)
- [x] point to each language-specific repo
- [x] brief notes for tracing system implementors
- [x] separate contributors page
- [x] host on opentracing.io without the redirect

**Comment by yurishkuro** [comment]
> point to each specific language-specific repo

this is done under APIs page. Do you have something else in mind?

**Comment by bensigelman** [comment]
yeah, fair point -- I was going to put it on the main page, too, but that's probably just going to fall out of date.

**Comment by yurishkuro** [comment]
For contributors page in the future we could use something like http://blossom.github.io/contributors/
