### ISSUE TITLE
who is behind opentracing?

### ISSUE THREAD

**Issue by CatTail** [opentracing/opentracing.github.io#93]
I think this is important and should add to website.

**Comment by yurishkuro** [comment]
http://opentracing.io/contributors/

**Comment by bensigelman** [comment]
(^^^ which is slightly out of date, admittedly)

**Comment by yurishkuro** [comment]
there have to be plugins to display a face book of contributors, like https://github.com/blossom/contributors

**Comment by CatTail** [comment]
I hear the news that [opentracing joined Twitter](https://twitter.com/zipkinproject/status/730246628792115201), I was curious how a open source project (non profit?) join an company?

**Comment by yurishkuro** [comment]
meaning we started an @OpenTracing feed on twitter, not joined the company.

https://twitter.com/opentracing
